module.exports = {
	assign: require('./assign/'),
	cid: require('./cid/'),
	deepExtend: require('./deep-extend/'),
	dev: require('./dev/'),
	diff: require('./diff/'),
	each: require('./diff/'),
	global: require('./global/'),
	import: require('./import/'),
	isArray: require('./is-array/'),
	isArrayLike: require('./is-array-like/'),
	isBrowserWindow: require('./is-browser-window/'),
	isEmptyObject: require('./is-empty-object/'),
	isFunction: require('./is-function/'),
	isNode: require('./is-node/'),
	isPlainObject: require('./is-plain-object/'),
	isPromise: require('./is-promise/'),
	isString: require('./is-string/'),
	isWebWorker: require('./is-web-worker/'),
	joinURIs: require('./join-uris/'),
	last: require('./last/'),
	makeArra: require('./make-array/'),
	setImmediate: require('./set-immediate/'),
	string: require('./string/'),
	types: require('./types/')
}
