language: node_js
node_js: node
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm run http-server &
  - sleep 2
script: npm run ci
addons:
  sauce_connect: true
  firefox: "52.2.1"
